# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://leylaKapi.github.io
title: Leyla's Blog
author: Leyla KAPI
subtitle: a developer, speaker and organizer
simple_search: http://google.com/search
description: I' m leyla . I' m computer engineer and web developer . This blog is like a diary, in which I wrote my experiences about software programming.

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "%a %e %b %Y, %l:%M %p"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email: leylakapi@gmail.com
# RSS feeds can list your email address if you like
email: leylakapi@gmail.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
pygments: true # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 10       # Posts in the sidebar Recent Posts section
excerpt_link: "Read more"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/advertise.html, custom/asides/gravatar.html, custom/asides/about.html, asides/recent_posts.html, asides/github.html, custom/asides/aboutmetwitter.html, asides/twitter.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: leylakapi
github_repo_count: 27
github_show_profile_link: true
github_skip_forks: true

#linkedin
linkedin_user: leylakapi

# Twitter
twitter_user: leylakapi
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: +leylakapi
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: leylasblog
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-49378525-1



#Gravatar
gravatar_email: leylakapi@gmail.com

